### ISSUE TITLE
Request "Pause" function

### ISSUE THREAD

**Issue by lawman5297** [EroticDevelopment/GuideMe#10]
I have requested this on Milovana but I thought I would put it here. Not sure this is the right way but here goes.
I am requestion a "Pause" function be added to the debug menu. This would work in much the same way as the "Delay" fucntion advances to the next page. The "Pause" button would stop the progression of the tease so that errors and corrections be made to the XML before continuning on.

**Comment by EroticDevelopment** [comment]
I've been working on this item and initial testing looks good. It has the potential to break things, so I'd like to do a bit more testing before releasing it. My current plan is to release this with the next release which will likely be in the next few weeks.

**Comment by lawman5297** [comment]
Fantastic! You are the man! After your explanation of how the timer works
within this I can see why it is not an easy thing. I had a few programming
classes in school; but that was a few years ago and it was VB, no Java. I
do understand the pain it takes to write code to make something work. My
son teaches Java and others but obviously I could not get him to work on
this lol. Thanks for the hard work.

**Comment by lawman5297** [comment]
I guess I should have asked if you need any help testing?
