### ISSUE TITLE
Global Button JavaScript / XML inconsistencies

### ISSUE THREAD

**Issue by EroticDevelopment** [EroticDevelopment/GuideMe#16]
Global Buttons added via JS cannot be removed via XML, and Global Buttons added via XML if removed with JS cannot be re-added.

**Comment by hiss-remi** [comment]
This should be fixed in 4.5 by [this commit](https://github.com/EroticDevelopment/GuideMe/pull/35/commits/e3fed8e34a2935998eaa9a604859925a416f5f89).

**Comment by EroticDevelopment** [comment]
This was resolved in v0.4.5. Closing.
