### ISSUE TITLE
Global Buttons persist across a new file load and restart

### ISSUE THREAD

**Issue by EroticDevelopment** [EroticDevelopment/GuideMe#17]
Global Buttons should be removed when loading a new XML file or restarting the current file

**Comment by hiss-remi** [comment]
This should be fixed in 4.5 by [this commit](https://github.com/EroticDevelopment/GuideMe/pull/35/commits/e3fed8e34a2935998eaa9a604859925a416f5f89).

**Comment by EroticDevelopment** [comment]
I agree, this issue was resolved in v0.4.5 release. Closing.
