### ISSUE TITLE
Missing XMLData for documentation

### ISSUE THREAD

**Issue by gnutp** [EroticDevelopment/GuideMe#8]
Hi, I'm trying to build the documentation to fix a minor error, but it seems like the XML definitions are missing from this repository.

After `npm install` and `npm run start` I get the following error:
```
Failed to compile

./src/documentation/XMLDocumentation.js
Module not found: Can't resolve './data/XMLData' in './src/documentation'

This error occurred during the build time and cannot be dismissed.
```

**Comment by EroticDevelopment** [comment]
Hi, Thanks for bringing this to my attention. The `data` directory that file is in inadvertently matched a rule in the root `.gitignore` file and I didn't notice. I've added a rule to the `gh-pages/.gitignore` file and committed `XMLData.js` in 42ed1eb

**Comment by gnutp** [comment]
Thanks, this works now :+1:
